### ISSUE TITLE
ret macro works strange in my code.

### ISSUE THREAD

**Issue by Pines** [tomtor/ulp-i2c#1]
i use stack in my code

1. include stack.s in main.s
2. alloc 100 in .bss of main.s
3. move r3, stack end (right after entry)
4. then call a subroutine (only set/clear gpio for debug) with ret at subroutine end.
 after calling jump subroutine, the following code wont be executed, so by now i gess ret jump to a wrong address.  i wonder could it be ulp compile version or setting up problem cause my ret work not correct. 

by the way thank you sir, your work is like lighting up a tower in the ocean.

**Comment by Pines** [comment]
i may not make that clear, code in subroutine run correct. but after call ret, it cant go back run code next where suntoutine called

**Comment by tomtor** [comment]
See https://www.esp32.com/viewtopic.php?f=2&t=3228

You need a patch for the assembler, the jump rx command produces wrong code. 

Espressif has not made new toolchain binairies available for download yet, so you will have to build them yourself.
This is easy on Linux (see link to forum),  but a bit more work on Windows.

**Comment by Pines** [comment]
ok, thank you so much

**Comment by Pines** [comment]
Hi, sir again.

i'm build this ulp compile tools myself on win7 under mingw32, and with no luck. make fail looks like cant find correct io.h fcntl.h

did you build it with windows, ... and how to do that

**Comment by tomtor** [comment]
I created a build with msys2 on a Windows-7 32-bit installation:

https://drive.google.com/open?id=0B3Q0BNAaAVQzV0JxWkpNU3ZVZjg

Also tested the as executable on a Windows-10 64 bit installation.

**Comment by Pines** [comment]
OK, thank you.

**Comment by Pines** [comment]
I'm in china, and now is morning,
I build a demo with this ulp tools-chain, and stack, i2c.s i2c-util.s finally have good i2c communication with mpu6050 sensor. 

I'm very exciting, this hard I2C left shift 1 bit thing trouble me for a week. i'll try do a little math dealing with data from mpu6050, that will be my goal. 

**Thank you Sir, answer my question. this ulp i2c tools is helpful. (5 star) **
