### ISSUE TITLE
Macro PSR

### ISSUE THREAD

**Issue by TemcoHeng** [tomtor/ulp-i2c#2]
Hi tomtor,I have confuse on macro psr.
`.macro psr sr=r1 pos=.
	.set _next2,(\pos+16)
	move \sr,_next2
	push \sr
.endm`
Why addr + 16 here? I think stack point should -16, please have a look. @tomtor

**Comment by tomtor** [comment]
It should point to the address of the first instruction following the macro, so +16 really is ok!
