### ISSUE TITLE
connecting MPU6050

### ISSUE THREAD

**Issue by Redstoned** [tomtor/ulp-i2c#4]
Hi,
I wanted to use the ULP-processor with the MPU6050 Gyro/accelerometer but I can't figure out how to change the example to get it working. The MPU6050 uses 8-bit registers.
Can someone please help me?

**Comment by aragaocarol** [comment]
> Hi, I wanted to use the ULP-processor with the MPU6050 Gyro/accelerometer but I can't figure out how to change the example to get it working. The MPU6050 uses 8-bit registers. Can someone please help me?

Hi, did you make it?

**Comment by cedricwritescode** [comment]
I did not figure it out, I gave up trying

**Comment by aragaocarol** [comment]
> I did not figure it out, I gave up trying

OK, thank you
